export const QUOTE_CALL_REQUEST = "QUOTE_CALL_REQUEST";
export const QUOTE_CALL_SUCCESS = "QUOTE_CALL_SUCCESS";
export const QUOTE_CALL_FAILURE = "QUOTE_CALL_FAILURE";
export const GIF_CALL_REQUEST = "GIF_CALL_REQUEST";
export const GIF_CALL_SUCCESS = "GIF_CALL_SUCCESS";
export const GIF_CALL_FAILURE = "GIF_CALL_FAILURE";